Josue nov19
adamrochwick/G19_Framework pull request #6
Opened 2020-11-18 17:49 UTC by JosueValladares

2020-11-18 20:38 UTC, isharoyan requested changes
move your comments from Feature file to Step definition class and change regression tag to @Regression (case sensitive)

2020-11-18 20:39 UTC, isharoyan requested changes
see previous comments

2020-11-18 20:40 UTC, isharoyan approved these changes

2020-11-18 20:42 UTC, isharoyan commented on target/test-classes/Features/MaintenanceTab/MaintenanceFeature.feature
> +      And I select a request in the "Scrap" column
did you duplicated two scenarios? and do you really need to parametrize the steps?

2020-11-19 22:52 UTC, adamrochwick commented on src/test/java/com/Briteerp/Runner/Runner1.java
> +            tags = " @Moving-request-forward-in-board-status",
remember to clear out your tags before you push! :)

2020-11-19 22:54 UTC, adamrochwick commented on src/test/java/com/Briteerp/StepDefinitions/Maintenance/Maintenance_POM.java
> -
Loto space my guy

2020-11-19 23:02 UTC, adamrochwick approved these changes
Looks solid!

2020-11-19 23:05 UTC, isharoyan approved these changes

2020-11-19 23:05 UTC, merged

2020-11-19 23:43 UTC, JosueValladares commented
Thank you guys for sharing your knowledge!!